import React, { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { AppState, FoodItem, RecipeInput } from '../types';
import { Button, Card, Chip, ChipRow, Field, Page, ScreenHeader, SectionTitle } from '../components/ui';
import { VoiceRecorder } from '../components/VoiceRecorder';
import { RecipeBuilder } from '../components/RecipeBuilder';
import { FoodDetailSheet } from '../components/FoodDetailSheet';
import { foodEmoji } from '../logic/foodVisual';
import { currentTime } from '../logic/time';
import { colors } from '../theme';

type CustomFoodValues = { name: string; brand?: string; servingGrams: number; calories: number; protein: number; carbs: number; fat: number };
export function LibraryScreen({ state, date, initialTime: _initialTime, timeZone, onSearch, onBarcode, onResolve, onTranscribe, onAdd, onCreateCustom, onCreateRecipe }: { state: AppState; date: string; initialTime: string; timeZone?: string; onSearch: (query: string) => Promise<FoodItem[]>; onBarcode: (code: string) => Promise<FoodItem>; onResolve: (phrase: string) => Promise<{ foods: FoodItem[]; quantities: Record<string, number>; notes: string[] }>; onTranscribe: (uri: string) => Promise<string>; onAdd: (food: FoodItem, quantity: number, eatenAt: string, note?: string) => void; onCreateCustom: (values: CustomFoodValues) => Promise<FoodItem>; onCreateRecipe: (input: RecipeInput) => Promise<FoodItem> }) {
  const [mode, setMode] = useState<'search' | 'voice' | 'scan'>('search'); const [query, setQuery] = useState(''); const [results, setResults] = useState<FoodItem[]>([]); const [selected, setSelected] = useState<FoodItem | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [scannerOpen, setScannerOpen] = useState(false); const [cameraPermission, requestCameraPermission] = useCameraPermissions(); const [showCustom, setShowCustom] = useState(false); const [showRecipe, setShowRecipe] = useState(false);
  const [customName, setCustomName] = useState(''); const [customBrand, setCustomBrand] = useState(''); const [customServing, setCustomServing] = useState('100'); const [customCalories, setCustomCalories] = useState(''); const [customProtein, setCustomProtein] = useState(''); const [customCarbs, setCustomCarbs] = useState(''); const [customFat, setCustomFat] = useState('');
  const recent = useMemo(() => {
    const foods = new Map(state.foods.map((food) => [food.id, food]));
    const seen = new Set<string>();
    return [...state.entries].sort((a, b) => b.enteredAt.localeCompare(a.enteredAt)).flatMap((entry) => {
      if (seen.has(entry.foodId)) return [];
      seen.add(entry.foodId);
      const food = foods.get(entry.foodId);
      return food ? [food] : [];
    }).slice(0, 10);
  }, [state.foods, state.entries]);
  const cookbook = useMemo(() => state.foods.filter((food) => food.tags?.includes('recipe') || food.source.source === 'manual'), [state.foods]);
  const reference = useMemo(() => state.foods.filter((food) => !cookbook.some((saved) => saved.id === food.id)), [state.foods, cookbook]);
  const recipeByFood = useMemo(() => new Map(state.recipes.map((recipe) => [recipe.foodId, recipe])), [state.recipes]);
  async function find() { if (!query.trim()) return; setBusy(true); try { const found = mode === 'voice' ? (await onResolve(query.trim())).foods : mode === 'scan' ? [await onBarcode(query.trim())] : await onSearch(query.trim()); const normalized = query.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim(); const exact = found.some((food) => `${food.name} ${(food.tags || []).join(' ')}`.toLowerCase().replace(/[^a-z0-9]+/g, ' ').includes(normalized)); setResults(found); setMessage(!found.length ? 'No match yet. Try a broader word, or add the food yourself from a label or as a dish.' : mode === 'search' && !exact ? `Showing related matches for “${query.trim()}”.` : ''); } catch (error) { setMessage(mode === 'search' ? 'The optional online catalogue is unavailable. Your local foods and manual tools still work.' : error instanceof Error ? error.message : 'Search failed.'); } finally { setBusy(false); } }
  async function transcribe(uri: string) { try { const transcript = await onTranscribe(uri); setQuery(transcript); setMessage('Transcript ready — review or edit it, then tap Search or Ask AI.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Voice failed.'); throw error; } }
  async function openScanner() { const permission = cameraPermission?.granted ? cameraPermission : await requestCameraPermission(); if (!permission.granted) return Alert.alert('Camera needed', 'Allow camera access to scan barcodes.'); setScannerOpen(true); }
  async function scanned(code: string) { setScannerOpen(false); setQuery(code); try { const food = await onBarcode(code); setResults([food]); setSelected(food); } catch { setMessage('Barcode not found. Create the product from its label.'); } }
  function quickAdd(food: FoodItem) { onAdd(food, food.serving.amount, currentTime(timeZone)); setMessage(`${food.name} logged now.`); }
  function openCustomForQuery() { setCustomName(query.trim()); setShowCustom(true); setShowRecipe(false); }
  async function createCustom() { const values = [customServing, customCalories, customProtein, customCarbs, customFat].map(Number); if (!customName.trim() || values.some((value) => !Number.isFinite(value)) || values[0] <= 0) return Alert.alert('Check values', 'Enter the food name and valid label values.'); const food = await onCreateCustom({ name: customName.trim(), brand: customBrand.trim() || undefined, servingGrams: values[0], calories: values[1], protein: values[2], carbs: values[3], fat: values[4] }); setSelected(food); setShowCustom(false); }
  const row = (food: FoodItem) => {
    const recipe = recipeByFood.get(food.id);
    const provenance = recipe?.reviewStatus === 'reference_reviewed' ? 'Reviewed reference' : recipe?.reviewStatus === 'ai_estimated' || food.tags?.includes('ai-created') ? 'AI estimate' : recipe ? 'Personal recipe' : food.source.source === 'usda' ? 'USDA reference' : food.source.source === 'openfoodfacts' ? 'Open Food Facts' : food.tags?.includes('starter') ? 'Starter reference' : 'Saved food';
    return <Pressable key={food.id} style={styles.row} onPress={() => setSelected(food)}><Text style={styles.emoji}>{foodEmoji(food)}</Text><View style={styles.copy}><Text style={styles.name} numberOfLines={2}>{food.name}</Text><Text style={styles.meta}>{provenance} · {food.nutrition.calories.toFixed(0)} kcal · {food.nutrition.protein.toFixed(0)}P · {food.nutrition.fat.toFixed(0)}F · {food.nutrition.carbs.toFixed(0)}C /100g</Text></View><Pressable style={styles.plus} onPress={(event) => { event.stopPropagation(); quickAdd(food); }}><Text style={styles.plusText}>+</Text></Pressable></Pressable>;
  };
  return <Page><ScreenHeader eyebrow="Food log" title="Find food" subtitle="Search, tap +, and log. Open an item only when you need quantities or details." />
    <ChipRow><Chip label="Search" selected={mode === 'search'} onPress={() => setMode('search')} /><Chip label="Ask AI" selected={mode === 'voice'} onPress={() => setMode('voice')} /><Chip label="Scan" selected={mode === 'scan'} onPress={() => setMode('scan')} /></ChipRow>
    {mode === 'scan' && scannerOpen ? <View style={styles.cameraFrame}><CameraView style={styles.camera} barcodeScannerSettings={{ barcodeTypes: ['ean13', 'ean8', 'upc_a', 'upc_e', 'code128'] }} onBarcodeScanned={({ data }) => void scanned(data)} /><View pointerEvents="none" style={styles.scanGuide} /></View> : null}{mode === 'scan' && !scannerOpen ? <Button label="Open barcode scanner" tone="secondary" onPress={() => void openScanner()} /> : null}
    <View style={styles.searchRow}><VoiceRecorder onRecorded={transcribe} disabled={busy || mode === 'scan'} /><Field value={query} onChangeText={(value) => { setQuery(value); setMessage(''); }} placeholder={mode === 'voice' ? 'Describe your meal' : mode === 'scan' ? 'Barcode number' : 'Search food or ingredient'} onSubmitEditing={() => void find()} style={styles.searchField} /><Button label={busy ? '…' : mode === 'voice' ? 'Ask AI' : 'Search'} compact onPress={() => void find()} /></View>{message ? <Text style={styles.message}>{message}</Text> : null}
    <View style={styles.actions}><Button label={showRecipe ? 'Close dish builder' : 'Build a dish'} compact tone="secondary" onPress={() => { setShowRecipe(!showRecipe); setShowCustom(false); }} /><Button label="Custom food" compact tone="ghost" onPress={openCustomForQuery} /></View>
    {!results.length && recent.length ? <><SectionTitle title="Recent" detail="quick add" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.recent}>{recent.slice(0, 7).map((food) => <Pressable key={food.id} style={styles.recentItem} onPress={() => setSelected(food)}><Text style={styles.recentEmoji}>{foodEmoji(food)}</Text><Text style={styles.recentName} numberOfLines={2}>{food.name}</Text><Pressable style={styles.recentPlus} onPress={(event) => { event.stopPropagation(); quickAdd(food); }}><Text style={styles.plusText}>+</Text></Pressable></Pressable>)}</ScrollView></> : null}
    {results.length ? <><SectionTitle title="Results" detail={`${results.length} shown`} /><Card style={styles.listCard}>{results.slice(0, 30).map(row)}</Card></> : <>
      <SectionTitle title="My cookbook" detail={`${cookbook.length} saved`} />
      <Card style={styles.listCard}>{cookbook.length ? cookbook.slice(0, 20).map(row) : <Text style={styles.emptyCopy}>Recipes and foods you create will live here. AI-created dishes are labelled as estimates until a source is reviewed.</Text>}</Card>
      <SectionTitle title="Reference catalog" detail={`${reference.length} on device`} />
      <Card style={styles.listCard}>{reference.slice(0, 20).map(row)}</Card>
    </>}
    {showRecipe ? <RecipeBuilder foods={state.foods} onSearch={onSearch} onResolve={onResolve} onSave={onCreateRecipe} onClose={() => setShowRecipe(false)} /> : null}
    {showCustom ? <Card><SectionTitle title="Custom food" detail="from package label" /><Field label="Name" value={customName} onChangeText={setCustomName} /><Field label="Brand" value={customBrand} onChangeText={setCustomBrand} /><Field label="Serving grams" value={customServing} onChangeText={setCustomServing} keyboardType="decimal-pad" /><View style={styles.grid}><Field label="Calories" value={customCalories} onChangeText={setCustomCalories} keyboardType="decimal-pad" style={styles.half} /><Field label="Protein" value={customProtein} onChangeText={setCustomProtein} keyboardType="decimal-pad" style={styles.half} /><Field label="Fat" value={customFat} onChangeText={setCustomFat} keyboardType="decimal-pad" style={styles.half} /><Field label="Carbs" value={customCarbs} onChangeText={setCustomCarbs} keyboardType="decimal-pad" style={styles.half} /></View><Button label="Save custom food" onPress={() => void createCustom()} /></Card> : null}
    <FoodDetailSheet food={selected} foods={state.foods} recipes={state.recipes} onClose={() => setSelected(null)} onAdd={(food, quantity) => onAdd(food, quantity, currentTime(timeZone))} />
  </Page>;
}

const styles = StyleSheet.create({ searchRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 7 }, searchField: { flex: 1 }, message: { color: colors.coral, fontSize: 9, lineHeight: 14, marginBottom: 10 }, recent: { gap: 9, paddingBottom: 14 }, recentItem: { width: 92, minHeight: 112, backgroundColor: colors.card, borderRadius: 17, borderWidth: 1, borderColor: colors.line, alignItems: 'center', padding: 9 }, recentEmoji: { fontSize: 31 }, recentName: { color: colors.ink, fontSize: 9, lineHeight: 12, fontWeight: '800', textAlign: 'center', marginTop: 5 }, recentPlus: { position: 'absolute', right: 5, top: 36, width: 28, height: 28, borderRadius: 14, backgroundColor: colors.paperDeep, alignItems: 'center', justifyContent: 'center' }, plusText: { color: colors.ink, fontSize: 21, lineHeight: 22 }, listCard: { paddingVertical: 2 }, emptyCopy: { color: colors.muted, lineHeight: 18, paddingVertical: 14 }, row: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 9 }, emoji: { width: 40, fontSize: 29, textAlign: 'center' }, copy: { flex: 1, flexShrink: 1 }, name: { color: colors.ink, fontSize: 12, lineHeight: 16, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 8, lineHeight: 12, marginTop: 5 }, plus: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.paperDeep, alignItems: 'center', justifyContent: 'center' }, actions: { flexDirection: 'row', gap: 7, marginVertical: 10 }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, half: { width: '48.5%' }, cameraFrame: { height: 240, borderRadius: 18, overflow: 'hidden', marginBottom: 10, backgroundColor: colors.ink }, camera: { flex: 1 }, scanGuide: { position: 'absolute', left: '12%', right: '12%', top: '33%', bottom: '33%', borderWidth: 2, borderColor: colors.gold, borderRadius: 12 } });
