import { themedStyles } from '../theme';
import React, { useMemo, useRef, useState } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { AppState, FoodItem, Recipe, RecipeInput } from '../types';
import { Button, Card, Chip, ChipRow, Field, Page, ScreenHeader, SectionTitle } from '../components/ui';
import { VoiceRecorder } from '../components/VoiceRecorder';
import { RecipeBuilder } from '../components/RecipeBuilder';
import { FoodDetailSheet } from '../components/FoodDetailSheet';
import { FoodEditorSheet } from '../components/FoodEditorSheet';
import { foodEmoji } from '../logic/foodVisual';
import { currentTime } from '../logic/time';
import { colors } from '../theme';
import { manualFoodIssue } from '../logic/manualInput';

type CustomFoodValues = { name: string; brand?: string; servingGrams: number; calories: number; protein: number; carbs: number; fat: number };
type ResolveResult = { foods: FoodItem[]; quantities: Record<string, number>; notes: string[] };

export function LibraryScreen({ state, date: _date, initialTime: _initialTime, timeZone, onSearch, onBarcode, onResolve, onTranscribe, onAdd, onCreateCustom, onCreateRecipe, onUpdateFood, onUpdateRecipe }: { state: AppState; date: string; initialTime: string; timeZone?: string; onSearch: (query: string) => Promise<FoodItem[]>; onBarcode: (code: string) => Promise<FoodItem>; onResolve: (phrase: string) => Promise<ResolveResult>; onTranscribe: (uri: string) => Promise<string>; onAdd: (food: FoodItem, quantity: number, eatenAt: string, note?: string) => Promise<void>; onCreateCustom: (values: CustomFoodValues) => Promise<FoodItem>; onCreateRecipe: (input: RecipeInput) => Promise<FoodItem>; onUpdateFood: (food: FoodItem) => Promise<void>; onUpdateRecipe: (recipeId: string, input: RecipeInput) => Promise<FoodItem> }) {
  const [mode, setMode] = useState<'search' | 'voice' | 'scan'>('search'); const [query, setQuery] = useState(''); const [results, setResults] = useState<FoodItem[]>([]); const [selected, setSelected] = useState<FoodItem | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [scannerOpen, setScannerOpen] = useState(false); const [cameraPermission, requestCameraPermission] = useCameraPermissions(); const [showCustom, setShowCustom] = useState(false); const [showRecipe, setShowRecipe] = useState(false); const [showCookbook, setShowCookbook] = useState(false); const [editingFood, setEditingFood] = useState<FoodItem | null>(null); const [editingRecipe, setEditingRecipe] = useState<Recipe | null>(null);
  const [customName, setCustomName] = useState(''); const [customBrand, setCustomBrand] = useState(''); const [customServing, setCustomServing] = useState('100'); const [customCalories, setCustomCalories] = useState(''); const [customProtein, setCustomProtein] = useState(''); const [customCarbs, setCustomCarbs] = useState(''); const [customFat, setCustomFat] = useState('');
  const customSaving = useRef(false); const quickSaving = useRef(false);
  const recipeByFood = useMemo(() => new Map(state.recipes.map((recipe) => [recipe.foodId, recipe])), [state.recipes]);
  const recent = useMemo(() => { const foods = new Map(state.foods.map((food) => [food.id, food])); const seen = new Set<string>(); return [...state.entries].sort((a, b) => b.enteredAt.localeCompare(a.enteredAt)).flatMap((entry) => { if (seen.has(entry.foodId)) return []; seen.add(entry.foodId); const food = foods.get(entry.foodId); return food ? [food] : []; }).slice(0, 10); }, [state.foods, state.entries]);
  const personalRecipes = useMemo(() => state.recipes.filter((recipe) => recipe.reviewStatus === 'manual' || !state.foods.find((food) => food.id === recipe.foodId)?.tags?.includes('ai-created')), [state.recipes, state.foods]);
  const aiRecipes = useMemo(() => state.recipes.filter((recipe) => !personalRecipes.some((personal) => personal.id === recipe.id)), [state.recipes, personalRecipes]);
  const personalFoods = useMemo(() => state.foods.filter((food) => food.source.source === 'manual' && !recipeByFood.has(food.id)), [state.foods, recipeByFood]);
  const reference = useMemo(() => state.foods.filter((food) => food.source.source !== 'manual' && !recipeByFood.has(food.id)), [state.foods, recipeByFood]);

  async function find() { if (!query.trim()) return; setBusy(true); try { const found = mode === 'voice' ? (await onResolve(query.trim())).foods : mode === 'scan' ? [await onBarcode(query.trim())] : await onSearch(query.trim()); const normalized = query.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim(); const exact = found.some((food) => `${food.name} ${(food.tags || []).join(' ')}`.toLowerCase().replace(/[^a-z0-9]+/g, ' ').includes(normalized)); setResults(found); setMessage(!found.length ? 'No exact match yet. Try one broader word, or create the food yourself.' : mode === 'search' && !exact ? `Showing related matches for “${query.trim()}”.` : ''); } catch (error) { setMessage(mode === 'search' ? 'The optional online catalogue is unavailable. Your saved foods and manual tools still work.' : error instanceof Error ? error.message : 'Search failed.'); } finally { setBusy(false); } }
  async function transcribe(uri: string) { try { const transcript = await onTranscribe(uri); setQuery(transcript); setMessage('Transcript ready — review it, then tap Ask AI.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Voice failed.'); throw error; } }
  async function openScanner() { const permission = cameraPermission?.granted ? cameraPermission : await requestCameraPermission(); if (!permission.granted) return Alert.alert('Camera needed', 'Allow camera access to scan barcodes.'); setScannerOpen(true); }
  async function scanned(code: string) { setScannerOpen(false); setQuery(code); try { const food = await onBarcode(code); setResults([food]); setSelected(food); } catch { setMessage('Barcode not found. Create the product from its label.'); } }
  async function quickAdd(food: FoodItem) {
    if (quickSaving.current) return;
    quickSaving.current = true;
    try { await onAdd(food, food.serving.amount, currentTime(timeZone)); setMessage(`${food.name} logged now.`); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Food was not saved. Please try again.'); }
    finally { quickSaving.current = false; }
  }
  function openCustomForQuery() { setCustomName(query.trim()); setShowCustom(true); setShowRecipe(false); }
  async function createCustom() {
    if (customSaving.current) return;
    const values: CustomFoodValues = { name: customName.trim(), brand: customBrand.trim() || undefined, servingGrams: Number(customServing), calories: Number(customCalories), protein: Number(customProtein), carbs: Number(customCarbs), fat: Number(customFat) };
    const issue = manualFoodIssue(values);
    if (issue) return Alert.alert('Check values', issue);
    customSaving.current = true; setBusy(true);
    try { const food = await onCreateCustom(values); setSelected(food); setShowCustom(false); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Custom food was not saved. Your entered values were kept.'); }
    finally { customSaving.current = false; setBusy(false); }
  }
  function editRecipe(recipe: Recipe) { setEditingRecipe(recipe); setShowRecipe(true); setShowCustom(false); }
  const mark = (food: FoodItem, style: 'row' | 'recent' = 'row') => food.imageUri ? <Image source={{ uri: food.imageUri }} style={style === 'recent' ? styles.recentPhoto : styles.photo} /> : <Text style={style === 'recent' ? styles.recentEmoji : styles.emoji}>{foodEmoji(food)}</Text>;
  const row = (food: FoodItem) => { const recipe = recipeByFood.get(food.id); const provenance = recipe?.reviewStatus === 'reference_reviewed' ? 'Reviewed reference' : recipe?.reviewStatus === 'ai_estimated' || food.tags?.includes('ai-created') ? 'AI recipe' : recipe ? 'Personal recipe' : food.source.source === 'usda' ? 'USDA reference' : food.source.source === 'openfoodfacts' ? 'Open Food Facts' : food.tags?.includes('starter') ? 'Starter reference' : 'Saved food'; return <Pressable key={food.id} style={styles.row} onPress={() => setSelected(food)}>{mark(food)}<View style={styles.copy}><Text style={styles.name} numberOfLines={2}>{food.name}</Text><Text style={styles.meta}>{provenance} · {food.nutrition.calories.toFixed(0)} kcal · {food.nutrition.protein.toFixed(0)}P · {food.nutrition.fat.toFixed(0)}F · {food.nutrition.carbs.toFixed(0)}C /100g</Text></View><Pressable style={styles.plus} hitSlop={8} onPress={(event) => { event.stopPropagation(); quickAdd(food); }}><Text style={styles.plusText}>+</Text></Pressable></Pressable>; };
  const recipeFoods = (recipes: Recipe[]) => recipes.map((recipe) => state.foods.find((food) => food.id === recipe.foodId)).filter((food): food is FoodItem => Boolean(food));

  return <Page><ScreenHeader eyebrow="Food log" title="Find food" subtitle="Search, tap +, or open a food to edit it." action={<Pressable style={styles.bookButton} onPress={() => { setShowCookbook((visible) => !visible); setResults([]); setMessage(''); }} accessibilityRole="button" accessibilityLabel="Open cookbook"><Ionicons name={showCookbook ? 'book' : 'book-outline'} size={22} color={colors.pine} /></Pressable>} />
    <ChipRow><Chip label="Search" selected={mode === 'search'} onPress={() => setMode('search')} /><Chip label="Ask AI" selected={mode === 'voice'} onPress={() => setMode('voice')} /><Chip label="Scan" selected={mode === 'scan'} onPress={() => setMode('scan')} /></ChipRow>
    {mode === 'scan' && scannerOpen ? <View style={styles.cameraFrame}><CameraView style={styles.camera} barcodeScannerSettings={{ barcodeTypes: ['ean13', 'ean8', 'upc_a', 'upc_e', 'code128'] }} onBarcodeScanned={({ data }) => void scanned(data)} /><View pointerEvents="none" style={styles.scanGuide} /></View> : null}{mode === 'scan' && !scannerOpen ? <Button label="Open barcode scanner" tone="secondary" onPress={() => void openScanner()} /> : null}
    <View style={styles.searchRow}><VoiceRecorder onRecorded={transcribe} disabled={busy || mode === 'scan'} /><Field value={query} onChangeText={(value) => { setQuery(value); setMessage(''); }} placeholder={mode === 'voice' ? 'Describe a meal' : mode === 'scan' ? 'Barcode number' : 'Search food or ingredient'} onSubmitEditing={() => void find()} style={styles.searchField} /><Button label={busy ? '…' : mode === 'voice' ? 'Ask AI' : 'Search'} compact onPress={() => void find()} /></View>{message ? <Text style={styles.message}>{message}</Text> : null}
    <View style={styles.actions}><Button label={showRecipe ? 'Close recipe editor' : 'Build a dish'} compact tone="secondary" onPress={() => { setShowRecipe((visible) => !visible); setEditingRecipe(null); setShowCustom(false); }} /><Button label="Custom food" compact tone="ghost" onPress={openCustomForQuery} /></View>
    {!results.length && recent.length ? <><SectionTitle title="Recent" detail="quick add" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.recent}>{recent.slice(0, 7).map((food) => <Pressable key={food.id} style={styles.recentItem} onPress={() => setSelected(food)}>{mark(food, 'recent')}<Text style={styles.recentName} numberOfLines={2}>{food.name}</Text><Pressable style={styles.recentPlus} hitSlop={8} onPress={(event) => { event.stopPropagation(); quickAdd(food); }}><Text style={styles.plusText}>+</Text></Pressable></Pressable>)}</ScrollView></> : null}
    {results.length ? <><SectionTitle title="Results" detail={`${results.length} shown`} /><Card style={styles.listCard}>{results.slice(0, 30).map(row)}</Card></> : null}
    {!results.length && showCookbook ? <><View style={styles.cookbookTitle}><Ionicons name="book" size={18} color={colors.pine} /><SectionTitle title="Your cookbook" detail="recipes and foods you control" /></View><SectionTitle title="Your recipes" detail={`${personalRecipes.length} created`} /><Card style={styles.listCard}>{personalRecipes.length ? recipeFoods(personalRecipes).map(row) : <Text style={styles.emptyCopy}>Recipes you build yourself appear here. Open a dish to edit ingredients, portions, emoji, or a photo.</Text>}</Card><SectionTitle title="AI recipes" detail={`${aiRecipes.length} created`} /><Card style={styles.listCard}>{aiRecipes.length ? recipeFoods(aiRecipes).map(row) : <Text style={styles.emptyCopy}>AI-created dishes are kept separate until you decide to edit them.</Text>}</Card><SectionTitle title="Custom foods" detail={`${personalFoods.length} created`} /><Card style={styles.listCard}>{personalFoods.length ? personalFoods.map(row) : <Text style={styles.emptyCopy}>Foods you add from a nutrition label appear here. Open one to edit its macros, emoji, or photo.</Text>}</Card></> : null}
    {!results.length && !showCookbook ? <Card style={styles.cookbookHint}><Ionicons name="book-outline" size={20} color={colors.pine} /><View style={styles.copy}><Text style={styles.name}>Your cookbook</Text><Text style={styles.meta}>Tap the book icon above to open recipes you created, AI recipes, and custom foods.</Text></View></Card> : null}
    {!results.length ? <><SectionTitle title="Reference catalog" detail={`${reference.length} on device`} /><Card style={styles.listCard}>{reference.slice(0, 20).map(row)}</Card></> : null}
    {showRecipe ? <RecipeBuilder key={editingRecipe?.id || 'new'} foods={state.foods} recipe={editingRecipe || undefined} recipeFood={editingRecipe ? state.foods.find((food) => food.id === editingRecipe.foodId) : undefined} onSearch={onSearch} onResolve={onResolve} onSave={(input) => editingRecipe ? onUpdateRecipe(editingRecipe.id, input) : onCreateRecipe(input)} onClose={() => { setShowRecipe(false); setEditingRecipe(null); }} /> : null}
    {showCustom ? <Card><SectionTitle title="Custom food" detail="from a package label" /><Field label="Name" value={customName} onChangeText={setCustomName} /><Field label="Brand" value={customBrand} onChangeText={setCustomBrand} /><Field label="Serving grams" value={customServing} onChangeText={setCustomServing} keyboardType="decimal-pad" /><View style={styles.grid}><Field label="Calories" value={customCalories} onChangeText={setCustomCalories} keyboardType="decimal-pad" style={styles.half} /><Field label="Protein" value={customProtein} onChangeText={setCustomProtein} keyboardType="decimal-pad" style={styles.half} /><Field label="Fat" value={customFat} onChangeText={setCustomFat} keyboardType="decimal-pad" style={styles.half} /><Field label="Carbs" value={customCarbs} onChangeText={setCustomCarbs} keyboardType="decimal-pad" style={styles.half} /></View><Text style={styles.customHint}>After saving, open the food to add an emoji or gallery photo.</Text><Button label="Save custom food" onPress={() => void createCustom()} /></Card> : null}
    <FoodDetailSheet food={selected} foods={state.foods} recipes={state.recipes} onClose={() => setSelected(null)} onAdd={(food, quantity) => onAdd(food, quantity, currentTime(timeZone))} onEditFood={(food) => setEditingFood(food)} onEditRecipe={editRecipe} />
    <FoodEditorSheet food={editingFood} onClose={() => setEditingFood(null)} onSave={onUpdateFood} />
  </Page>;
}

const styles = themedStyles(() => ({
  bookButton: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperDeep }, searchRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 7 }, searchField: { flex: 1 }, message: { color: colors.coral, fontSize: 9, lineHeight: 14, marginBottom: 10 }, recent: { gap: 9, paddingBottom: 14 }, recentItem: { width: 94, minHeight: 128, backgroundColor: colors.card, borderRadius: 17, borderWidth: 1, borderColor: colors.line, alignItems: 'center', padding: 9 }, recentEmoji: { fontSize: 31, height: 39 }, recentPhoto: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.paperDeep }, recentName: { color: colors.ink, fontSize: 9, lineHeight: 12, fontWeight: '800', textAlign: 'center', marginTop: 5 }, recentPlus: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.paperDeep, alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-end', marginTop: 'auto' }, plusText: { color: colors.ink, fontSize: 21, lineHeight: 22 }, listCard: { paddingVertical: 2 }, emptyCopy: { color: colors.muted, lineHeight: 18, paddingVertical: 14 }, row: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderColor: colors.line, paddingHorizontal: 5, paddingVertical: 9 }, emoji: { width: 40, fontSize: 29, textAlign: 'center' }, photo: { width: 37, height: 37, borderRadius: 11, backgroundColor: colors.paperDeep, marginHorizontal: 2 }, copy: { flex: 1, flexShrink: 1 }, name: { color: colors.ink, fontSize: 12, lineHeight: 16, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 8, lineHeight: 12, marginTop: 5 }, plus: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.paperDeep, alignItems: 'center', justifyContent: 'center', marginLeft: 2 }, actions: { flexDirection: 'row', gap: 7, marginVertical: 10 }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, half: { width: '48.5%' }, customHint: { color: colors.muted, fontSize: 9, lineHeight: 13, marginBottom: 10 }, cookbookHint: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 }, cookbookTitle: { flexDirection: 'row', alignItems: 'center', gap: 7 }, cameraFrame: { height: 240, borderRadius: 18, overflow: 'hidden', marginBottom: 10, backgroundColor: colors.ink }, camera: { flex: 1 }, scanGuide: { position: 'absolute', left: '12%', right: '12%', top: '33%', bottom: '33%', borderWidth: 2, borderColor: colors.gold, borderRadius: 12 }
}));
