import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Share, StyleSheet, Text, View } from 'react-native';
import { AppState, ProfileInput } from '../types';
import { Button, Card, Chip, ChipRow, Field, Page, ScreenHeader, SectionTitle } from '../components/ui';
import { CalendarPicker } from '../components/CalendarPicker';
import { buildDailySeries, latestWeightByDate } from '../logic/analytics';
import { weeklyChangeForGoal } from '../logic/goals';
import { cmToFeetInches, feetInchesToCm, kgToLb, lbToKg } from '../logic/units';
import { activeTheme as loadedTheme, AppThemeName, colors, themeOptions } from '../theme';
import { StravaStatus } from '../services/agentClient';
import { HealthConnectStatus } from '../services/healthConnect';

export function ProfileScreen({ state, date, status, strava, healthConnect, audioConfigured, codexResolverEnabled, activeTheme = loadedTheme, onThemeChange, onSave, onSync, onLoadDemo, onExport, onImport, onConnectStrava, onSyncStrava, onConnectHealth, onOpenHealthSettings, onRefreshIntegrations }: {
  state: AppState; date: string; status: string; strava: StravaStatus | null; healthConnect: HealthConnectStatus | null; audioConfigured: boolean | null; codexResolverEnabled: boolean | null;
  activeTheme?: AppThemeName; onThemeChange: (theme: AppThemeName) => void;
  onSave: (profile: ProfileInput) => void; onSync: () => void; onLoadDemo: () => void; onExport: () => string; onImport: (text: string) => void;
  onConnectStrava: () => void; onSyncStrava: () => void; onConnectHealth: () => void; onOpenHealthSettings: () => void; onRefreshIntegrations: () => void;
}) {
  const profile = state.profile;
  const initialHeight = profile?.heightCm || 175; const initialImperialHeight = cmToFeetInches(initialHeight);
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(profile?.displayName || ''); const [sex, setSex] = useState<ProfileInput['sex']>(profile?.sex || 'male'); const [age, setAge] = useState(String(profile?.ageYears || 30));
  const [heightUnit, setHeightUnit] = useState<'cm' | 'ft'>(profile?.preferredHeightUnit || 'cm'); const [height, setHeight] = useState(String(initialHeight)); const [feet, setFeet] = useState(String(initialImperialHeight.feet)); const [inches, setInches] = useState(String(initialImperialHeight.inches));
  const [weightUnit, setWeightUnit] = useState<'kg' | 'lb'>(profile?.preferredWeightUnit || 'kg'); const [weight, setWeight] = useState(String(profile?.preferredWeightUnit === 'lb' ? kgToLb(profile.bodyWeightKg).toFixed(1) : profile?.bodyWeightKg || 75)); const [target, setTarget] = useState(String(profile?.preferredWeightUnit === 'lb' && profile.targetWeightKg ? kgToLb(profile.targetWeightKg).toFixed(1) : profile?.targetWeightKg || 70));
  const [factor, setFactor] = useState(String(profile?.activityFactor || 1.4)); const [mode, setMode] = useState<'lose' | 'maintain' | 'gain'>(profile?.goalMode === 'lose' || profile?.goalMode === 'gain' ? profile.goalMode : 'maintain'); const [intensity, setIntensity] = useState<'gentle' | 'moderate' | 'aggressive'>(profile?.goalIntensity || 'moderate'); const [targetDate, setTargetDate] = useState(profile?.targetDate || date);
  const [backupText, setBackupText] = useState(''); const [showRestore, setShowRestore] = useState(false);

  useEffect(() => {
    if (!profile) return;
    const imperial = cmToFeetInches(profile.heightCm); const preferredHeight = profile.preferredHeightUnit || 'cm'; const preferredWeight = profile.preferredWeightUnit || 'kg';
    setName(profile.displayName || ''); setSex(profile.sex); setAge(String(profile.ageYears)); setHeightUnit(preferredHeight); setHeight(String(profile.heightCm)); setFeet(String(imperial.feet)); setInches(String(imperial.inches)); setWeightUnit(preferredWeight); setWeight(String(preferredWeight === 'lb' ? kgToLb(profile.bodyWeightKg).toFixed(1) : profile.bodyWeightKg)); setTarget(String(preferredWeight === 'lb' && profile.targetWeightKg ? kgToLb(profile.targetWeightKg).toFixed(1) : profile.targetWeightKg || '')); setFactor(String(profile.activityFactor)); setMode(profile.goalMode === 'lose' || profile.goalMode === 'gain' ? profile.goalMode : 'maintain'); setIntensity(profile.goalIntensity || 'moderate'); setTargetDate(profile.targetDate || date);
  }, [profile?.updatedAt]);

  const year = useMemo(() => {
    const series = buildDailySeries({ endDate: date, days: 365, entries: state.entries, foods: state.foods, activities: state.activities, goals: state.goals, profile });
    const logged = series.filter((day) => day.logged); const startDate = series[0]?.date || date;
    const weights = latestWeightByDate(state.weights).filter((item) => item.date >= startDate && item.date <= date);
    const firstWeight = weights[0]?.weightKg; const currentWeight = weights[weights.length - 1]?.weightKg ?? profile?.bodyWeightKg;
    const targetWeight = profile?.targetWeightKg; const startingDistance = firstWeight != null && targetWeight != null ? Math.abs(firstWeight - targetWeight) : 0;
    const remainingDistance = currentWeight != null && targetWeight != null ? Math.abs(currentWeight - targetWeight) : 0;
    const goalProgress = profile?.goalMode === 'maintain' ? null : startingDistance > 0 ? Math.max(0, Math.min(100, ((startingDistance - remainingDistance) / startingDistance) * 100)) : null;
    const activities = state.activities.filter((item) => item.date >= startDate && item.date <= date);
    return {
      loggedDays: logged.length,
      averageCalories: logged.length ? Math.round(logged.reduce((sum, day) => sum + day.calories, 0) / logged.length) : 0,
      activeHours: Math.round(activities.reduce((sum, item) => sum + item.durationMinutes, 0) / 6) / 10,
      weightChange: firstWeight != null && currentWeight != null && weights.length > 1 ? currentWeight - firstWeight : null,
      currentWeight,
      goalProgress
    };
  }, [date, state.entries, state.foods, state.activities, state.goals, state.weights, profile]);

  const input = useMemo<ProfileInput | null>(() => {
    const heightCm = heightUnit === 'cm' ? Number(height) : feetInchesToCm(Number(feet), Number(inches)); const bodyWeightKg = weightUnit === 'kg' ? Number(weight) : lbToKg(Number(weight)); const targetWeightKg = mode === 'maintain' ? bodyWeightKg : weightUnit === 'kg' ? Number(target) : lbToKg(Number(target));
    const base = { displayName: name.trim() || undefined, sex, ageYears: Number(age), heightCm, bodyWeightKg, targetWeightKg, activityFactor: Number(factor), goalMode: mode, goalIntensity: intensity, targetDate, onboardingComplete: true, preferredHeightUnit: heightUnit, preferredWeightUnit: weightUnit, adaptiveTdee: profile?.adaptiveTdee, adaptiveTdeeUpdatedAt: profile?.adaptiveTdeeUpdatedAt };
    if (![base.ageYears, base.heightCm, base.bodyWeightKg, base.targetWeightKg, base.activityFactor].every(Number.isFinite)) return null;
    return { ...base, weeklyWeightChangeKg: weeklyChangeForGoal(base) };
  }, [name, sex, age, heightUnit, height, feet, inches, weightUnit, weight, target, factor, mode, intensity, targetDate, profile?.adaptiveTdee, profile?.adaptiveTdeeUpdatedAt]);

  function switchHeight(next: 'cm' | 'ft') { if (next === heightUnit) return; if (next === 'ft') { const value = cmToFeetInches(Number(height)); setFeet(String(value.feet)); setInches(String(value.inches)); } else setHeight(String(Math.round(feetInchesToCm(Number(feet), Number(inches))))); setHeightUnit(next); }
  function switchWeight(next: 'kg' | 'lb') { if (next === weightUnit) return; if (next === 'lb') { setWeight(String(kgToLb(Number(weight)).toFixed(1))); setTarget(String(kgToLb(Number(target)).toFixed(1))); } else { setWeight(String(lbToKg(Number(weight)).toFixed(1))); setTarget(String(lbToKg(Number(target)).toFixed(1))); } setWeightUnit(next); }
  function save() { if (!input || input.ageYears < 13 || input.ageYears > 120 || input.heightCm < 80 || input.heightCm > 260 || input.bodyWeightKg < 25 || input.bodyWeightKg > 500 || input.activityFactor < 1.1 || input.activityFactor > 2.5) return Alert.alert('Check your profile', 'One or more values are invalid.'); onSave(input); setEditing(false); }
  async function exportBackup() { const text = onExport(); setBackupText(text); await Share.share({ title: `FitnessMacro backup ${date}`, message: text }); }
  function displayWeight(value?: number) { if (value == null) return 'No check-in'; return profile?.preferredWeightUnit === 'lb' ? `${kgToLb(value).toFixed(1)} lb` : `${value.toFixed(1)} kg`; }
  const goalLabel = profile?.goalMode === 'lose' ? 'Lose weight' : profile?.goalMode === 'gain' ? 'Build weight / muscle' : 'Maintain weight';

  return <Page>
    <ScreenHeader eyebrow="Your local account" title={profile?.displayName || 'You'} subtitle="Your profile, annual progress, integrations, and data ownership in one place." />
    <Card dark><View style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>{(profile?.displayName || 'Y').slice(0, 1).toUpperCase()}</Text></View><View style={styles.identityCopy}><Text style={styles.identityName}>{profile?.displayName || 'Local profile'}</Text><Text style={styles.identityMeta}>{profile?.ageYears} years · {profile?.heightCm.toFixed(0)} cm · {displayWeight(year.currentWeight)}</Text></View></View></Card>

    <View style={styles.editAction}><Button label={editing ? 'Cancel editing' : 'Edit profile'} tone={editing ? 'ghost' : 'secondary'} compact onPress={() => setEditing(!editing)} /></View>

    <SectionTitle title="Appearance" detail="stored only on this phone" /><Card><ChipRow>{themeOptions.map((theme) => <Chip key={theme.key} label={theme.label} selected={activeTheme === theme.key} onPress={() => onThemeChange(theme.key)} />)}</ChipRow><Text style={styles.systemDetail}>{themeOptions.find((theme) => theme.key === activeTheme)?.detail} Changing themes reloads the interface once so every screen updates together.</Text></Card>

    {!editing ? <>
      <SectionTitle title="Goal at a glance" detail={profile?.targetDate ? `by ${profile.targetDate}` : 'current plan'} />
      <Card><View style={styles.summaryRow}><View><Text style={styles.kicker}>DIRECTION</Text><Text style={styles.summaryValue}>{goalLabel}</Text></View><View style={styles.rightSummary}><Text style={styles.kicker}>TARGET</Text><Text style={styles.summaryValue}>{profile?.goalMode === 'maintain' ? displayWeight(year.currentWeight) : displayWeight(profile?.targetWeightKg)}</Text></View></View><Text style={styles.goalDetail}>{profile?.goalIntensity || 'moderate'} pace · activity factor {profile?.activityFactor.toFixed(2)} · {profile?.preferredHeightUnit || 'cm'} and {profile?.preferredWeightUnit || 'kg'} preferred</Text>{year.goalProgress != null ? <><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${year.goalProgress}%` }]} /></View><Text style={styles.progressCaption}>{year.goalProgress.toFixed(0)}% of the recorded weight journey completed</Text></> : <Text style={styles.progressCaption}>Maintenance progress is measured by consistency and weight trend.</Text>}</Card>

      <SectionTitle title="Past 365 days" detail="your recorded progress" />
      <View style={styles.metricGrid}><Metric label="Logged days" value={String(year.loggedDays)} detail={`${Math.round(year.loggedDays / 3.65)}% coverage`} /><Metric label="Average intake" value={year.averageCalories ? `${year.averageCalories}` : '—'} detail="kcal on logged days" /><Metric label="Weight change" value={year.weightChange == null ? '—' : `${year.weightChange > 0 ? '+' : ''}${profile?.preferredWeightUnit === 'lb' ? kgToLb(year.weightChange).toFixed(1) : year.weightChange.toFixed(1)}`} detail={profile?.preferredWeightUnit === 'lb' ? 'lb from check-ins' : 'kg from check-ins'} /><Metric label="Activity" value={`${year.activeHours}`} detail="hours recorded" /></View>
    </> : <>
      <Card><SectionTitle title="Personal information" detail="edit mode" /><Field label="Name" value={name} onChangeText={setName} /><Text style={styles.label}>SEX USED BY BMR EQUATION</Text><ChipRow>{(['male', 'female', 'other'] as const).map((value) => <Chip key={value} label={value} selected={sex === value} onPress={() => setSex(value)} />)}</ChipRow><Field label="Age" value={age} onChangeText={setAge} keyboardType="number-pad" />
        <Text style={styles.label}>HEIGHT UNIT</Text><ChipRow><Chip label="Centimeters" selected={heightUnit === 'cm'} onPress={() => switchHeight('cm')} /><Chip label="Feet & inches" selected={heightUnit === 'ft'} onPress={() => switchHeight('ft')} /></ChipRow>{heightUnit === 'cm' ? <Field label="Height (cm)" value={height} onChangeText={setHeight} keyboardType="decimal-pad" /> : <View style={styles.columns}><Field label="Feet" value={feet} onChangeText={setFeet} keyboardType="number-pad" style={styles.half} /><Field label="Inches" value={inches} onChangeText={setInches} keyboardType="decimal-pad" style={styles.half} /></View>}
        <Text style={styles.label}>WEIGHT UNIT</Text><ChipRow><Chip label="Kilograms" selected={weightUnit === 'kg'} onPress={() => switchWeight('kg')} /><Chip label="Pounds" selected={weightUnit === 'lb'} onPress={() => switchWeight('lb')} /></ChipRow><Field label={`Current weight (${weightUnit})`} value={weight} onChangeText={setWeight} keyboardType="decimal-pad" />
      </Card>
      <Card><SectionTitle title="Goal preferences" detail="edit mode" /><ChipRow><Chip label="Lose weight" selected={mode === 'lose'} onPress={() => setMode('lose')} /><Chip label="Maintain weight" selected={mode === 'maintain'} onPress={() => setMode('maintain')} /><Chip label="Build weight / muscle" selected={mode === 'gain'} onPress={() => setMode('gain')} /></ChipRow>{mode !== 'maintain' ? <Field label={`Target weight (${weightUnit})`} value={target} onChangeText={setTarget} keyboardType="decimal-pad" /> : null}<CalendarPicker label="TARGET DATE" value={targetDate} minDate={date} onChange={setTargetDate} /><Text style={styles.label}>PACE</Text><ChipRow>{(['gentle', 'moderate', 'aggressive'] as const).map((value) => <Chip key={value} label={value} selected={intensity === value} onPress={() => setIntensity(value)} />)}</ChipRow><Field label="Typical activity factor" value={factor} onChangeText={setFactor} keyboardType="decimal-pad" /><Button label="Save profile and goals" onPress={save} /></Card>
    </>}

    <SectionTitle title="Connections" detail="your services" /><Card><Text style={styles.systemTitle}>Health Connect · {healthConnect?.permissionGranted ? 'calorie sync active' : healthConnect?.developmentBuildRequired ? 'development build required' : healthConnect?.available ? 'ready for permission' : 'checking availability'}</Text><Text style={styles.systemDetail}>{healthConnect?.message || 'FitnessMacro reads only Strava calorie records and refreshes them when the app opens.'}</Text><View style={styles.integrationActions}>{healthConnect?.permissionGranted ? <Button label="Health settings" compact tone="secondary" onPress={onOpenHealthSettings} /> : <Button label="Connect Health" compact tone="secondary" onPress={onConnectHealth} />}<Button label="Refresh connections" compact tone="ghost" onPress={onRefreshIntegrations} /></View><Text style={styles.systemTitle}>Strava API · {strava?.connected ? 'connected fallback' : 'not needed for Health Connect'}</Text>{strava?.connected ? <View style={styles.integrationActions}><Button label="Sync Strava API" compact tone="ghost" onPress={onSyncStrava} /></View> : strava?.configured ? <View style={styles.integrationActions}><Button label="Connect API fallback" compact tone="ghost" onPress={onConnectStrava} /></View> : null}<Text style={styles.systemTitle}>Voice · {audioConfigured ? 'transcription ready' : audioConfigured === false ? 'transcription not configured' : 'status unavailable'}</Text><Text style={styles.systemDetail}>{audioConfigured ? 'Speech is transcribed by your configured engine, then passed to the action planner.' : 'Configure either free Groq Whisper or local Whisper in agent/.env, then keep the PC agent running.'}</Text><Text style={styles.systemTitle}>App agent · {codexResolverEnabled ? 'full control plane enabled' : 'PC agent unavailable'}</Text></Card>

    <SectionTitle title="Backup & local system" detail="data ownership" /><Card><Text style={styles.systemDetail}>Portable JSON includes your profile, recipes, foods, diary, weights, activities, and targets. Credentials and raw audio are excluded.</Text><Button label="Share portable backup" onPress={() => void exportBackup()} /><View style={styles.gap} /><Button label={showRestore ? 'Hide restore box' : 'Restore backup'} tone="secondary" onPress={() => setShowRestore(!showRestore)} />{showRestore ? <><Field label="Paste complete backup JSON" value={backupText} onChangeText={setBackupText} multiline autoCapitalize="none" /><Button label="Import and replace local data" tone="danger" onPress={() => Alert.alert('Replace local data?', 'The pasted backup will become the active local account.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Import', onPress: () => onImport(backupText) }])} /></> : null}<View style={styles.gap} /><Button label="Load demo history" tone="ghost" onPress={() => Alert.alert('Load demo history?', 'This refreshes 60 days of demonstration records.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Load', onPress: onLoadDemo }])} /><View style={styles.divider} /><Text style={styles.systemTitle}>{state.pendingOperations.length ? `${state.pendingOperations.length} changes waiting for PC` : 'Local changes synchronized'}</Text><Text style={styles.systemDetail}>{status}</Text><Button label="Sync everything with PC" tone="secondary" onPress={onSync} /></Card>
    <Text style={styles.footer}>LOCAL-FIRST · SCHEMA 5</Text>
  </Page>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) {
  return <Card style={styles.metric}><Text style={styles.kicker}>{label.toUpperCase()}</Text><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricDetail}>{detail}</Text></Card>;
}

const styles = StyleSheet.create({ identity: { flexDirection: 'row', alignItems: 'center', gap: 13 }, identityCopy: { flex: 1 }, avatar: { width: 52, height: 52, borderRadius: 26, backgroundColor: colors.coral, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontSize: 22, fontWeight: '900' }, identityName: { color: colors.white, fontFamily: 'serif', fontSize: 25, fontWeight: '900' }, identityMeta: { color: colors.faint, marginTop: 3 }, editAction: { alignItems: 'flex-end', marginTop: -5 }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, rightSummary: { alignItems: 'flex-end', flex: 1 }, kicker: { color: colors.muted, fontSize: 9, fontWeight: '900', letterSpacing: 1.1 }, summaryValue: { color: colors.ink, fontSize: 18, fontWeight: '900', marginTop: 5 }, goalDetail: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 14 }, progressTrack: { height: 9, borderRadius: 6, backgroundColor: colors.line, overflow: 'hidden', marginTop: 15 }, progressFill: { height: '100%', borderRadius: 6, backgroundColor: colors.coral }, progressCaption: { color: colors.muted, fontSize: 10, marginTop: 7 }, metricGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, metric: { width: '48.5%', minHeight: 118 }, metricValue: { color: colors.ink, fontFamily: 'serif', fontSize: 27, fontWeight: '900', marginTop: 9 }, metricDetail: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, label: { color: colors.muted, fontSize: 9, fontWeight: '900', letterSpacing: 1.2, marginBottom: 7 }, columns: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, half: { width: '48.5%' }, systemTitle: { color: colors.ink, fontWeight: '900', marginTop: 10 }, systemDetail: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 3, marginBottom: 8 }, integrationActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 9 }, divider: { height: 1, backgroundColor: colors.line, marginVertical: 12 }, footer: { color: colors.faint, fontSize: 9, letterSpacing: 1.2, fontWeight: '800', textAlign: 'center', marginTop: 12 }, gap: { height: 8 } });
